// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWMS.Infrastructure;

#nullable disable

namespace SimpleWMS.Infrastructure.Migrations
{
    [DbContext(typeof(SimpleWmsDbContext))]
    partial class SimpleWmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleWMS.Domain.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CargoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerBarcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerBarcode")
                        .IsUnique();

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("SimpleWMS.Domain.Entities.Container", b =>
                {
                    b.OwnsMany("SimpleWMS.Domain.Entities.Instance", "Instances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContainerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PostingBarcode")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ContainerId");

                            b1.HasIndex("PostingBarcode")
                                .IsUnique();

                            b1.ToTable("Instances", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
